

CREATE TABLE clm.referentiel_foncier (
    id integer DEFAULT nextval('clm.referentiel_foncier_id_seq'::regclass) NOT NULL,
    geom public.geometry(MultiPolygon,2154),
    commune character varying,
    echeance character varying,
    vocation character varying DEFAULT 'A préciser'::character varying,
    niveau_enjeu_clm character varying,
    adresse character varying,
    priorite_terrain_avp character varying,
    origine_reperage character varying,
    typologie_commune character varying,
    nom_site character varying,
    nom_detail character varying,
    commentaire character varying,
    commentaire_clm character varying,
    etat_bati character varying,
    photo1 character varying,
    photo2 character varying,
    photo3 character varying,
    zonage text,
    urba_typezonage text,
    zonage_libelle text,
    nature_foncier text,
    surface integer,
    nbat integer,
    nlocal integer,
    spevtot integer,
    nloclog integer,
    nb_loc_commerciaux_existants integer,
    nloccomsec integer,
    nloccomter integer,
    nb_logements_existants integer,
    nloghvac integer,
    surface_cadastrale integer,
    surface_commune integer,
    surface_epci integer,
    surf_cad_epf integer,
    surface_autre_public integer,
    surface_copropriete integer,
    surface_prive integer,
    nb_uf_non_maitrisee integer,
    nb_proprietaires integer,
    nb_parcelles integer,
    urba_prescriptions text,
    estimation_logements_theorique numeric,
    pct_tvb numeric,
    pct_tache_urbaine numeric,
    intervention_epf_active text,
    intervention_epf_active_nom_operation text,
    env_agricoleext_surf numeric,
    env_agricoleext_pct numeric,
    env_ao_surf numeric,
    env_ao_pct numeric,
    env_bo_surf numeric,
    env_bo_pct numeric,
    env_ma_surf numeric,
    env_ma_pct numeric,
    env_mh_surf numeric,
    env_mh_pct numeric,
    env_mt_surf numeric,
    env_mt_pct numeric,
    surface_amenageur_public integer,
    env_score_total integer,
    risques_ppri text,
    risques_pprm text,
    risques_pprt text,
    risques_argiles text,
    risques_cavites text,
    env_znieff text,
    surf_totale_maitrisee numeric,
    pct_surf_maitrisee numeric,
    ndroit_non_maitrise integer,
    note_morcellement integer,
    note_occupation integer,
    note_etat_bati integer,
    note_durete integer,
    classe_durete_fonciere text,
    env_especes_protegees text,
    env_especes_protegees_surf numeric,
    env_especes_protegees_pct numeric,
    site_priorise text DEFAULT 'Non'::text,
    typologie_commune_plh text,
    basias_nb_sites integer,
    basias_detail text,
    note_environnement integer,
    note_ppri integer,
    note_espace_protege integer,
    commune_origine text,
    photo4 text,
    vu_terrain text DEFAULT 'non'::text,
    outils_plu text,
    etude_prealable text,
    competence text,
    intervention text,
    portage text,
    echeance_ct_lt text,
    surface_creee integer,
    nb_logts_crees integer,
    couts_acquisition integer,
    couts_travaux_deconstruction integer,
    couts_travaux_depollution integer,
    couts_travaux integer,
    couts_etudes integer,
    montant_total_couts integer,
    montant_total_recettes integer,
    solde integer,
    filiere text,
    CONSTRAINT geometry_is_valid_check CHECK (public.st_isvalid(geom))
);


ALTER TABLE ONLY clm.referentiel_foncier
    ADD CONSTRAINT referentiel_foncier_pkey PRIMARY KEY (id);


CREATE INDEX sidx_referentiel_foncier_geom ON clm.referentiel_foncier USING gist (geom);
